# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Works\Website\dogemsg\client\dogemsg.ui'
#
# Created: Fri Jul 18 22:31:41 2014
#      by: PyQt4 UI code generator 4.11.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(631, 596)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(10, 10, 611, 541))
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab_Message = QtGui.QWidget()
        self.tab_Message.setObjectName(_fromUtf8("tab_Message"))
        self.txtChatWindows = QtGui.QTextBrowser(self.tab_Message)
        self.txtChatWindows.setGeometry(QtCore.QRect(160, 20, 421, 411))
        self.txtChatWindows.setObjectName(_fromUtf8("txtChatWindows"))
        self.txtSend = QtGui.QTextEdit(self.tab_Message)
        self.txtSend.setGeometry(QtCore.QRect(160, 440, 361, 71))
        self.txtSend.setObjectName(_fromUtf8("txtSend"))
        self.cmdSend = QtGui.QPushButton(self.tab_Message)
        self.cmdSend.setGeometry(QtCore.QRect(530, 440, 51, 31))
        self.cmdSend.setObjectName(_fromUtf8("cmdSend"))
        self.cmdPull = QtGui.QPushButton(self.tab_Message)
        self.cmdPull.setGeometry(QtCore.QRect(530, 480, 51, 31))
        self.cmdPull.setObjectName(_fromUtf8("cmdPull"))
        self.listContact = QtGui.QListWidget(self.tab_Message)
        self.listContact.setGeometry(QtCore.QRect(10, 20, 131, 491))
        self.listContact.setObjectName(_fromUtf8("listContact"))
        item = QtGui.QListWidgetItem()
        self.listContact.addItem(item)
        item = QtGui.QListWidgetItem()
        self.listContact.addItem(item)
        item = QtGui.QListWidgetItem()
        self.listContact.addItem(item)
        self.tabWidget.addTab(self.tab_Message, _fromUtf8(""))
        self.tab_Contact = QtGui.QWidget()
        self.tab_Contact.setObjectName(_fromUtf8("tab_Contact"))
        self.tableContact = QtGui.QTableWidget(self.tab_Contact)
        self.tableContact.setGeometry(QtCore.QRect(20, 20, 481, 471))
        self.tableContact.setLineWidth(1)
        self.tableContact.setShowGrid(True)
        self.tableContact.setGridStyle(QtCore.Qt.SolidLine)
        self.tableContact.setObjectName(_fromUtf8("tableContact"))
        self.tableContact.setColumnCount(3)
        self.tableContact.setRowCount(1)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tableContact.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableContact.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableContact.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableContact.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tableContact.setItem(0, 0, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tableContact.setItem(0, 1, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tableContact.setItem(0, 2, item)
        self.tableContact.horizontalHeader().setCascadingSectionResizes(True)
        self.tableContact.horizontalHeader().setDefaultSectionSize(120)
        self.tableContact.verticalHeader().setVisible(False)
        self.cmdAddContact = QtGui.QPushButton(self.tab_Contact)
        self.cmdAddContact.setGeometry(QtCore.QRect(510, 20, 71, 31))
        self.cmdAddContact.setObjectName(_fromUtf8("cmdAddContact"))
        self.cmdDelContact = QtGui.QPushButton(self.tab_Contact)
        self.cmdDelContact.setGeometry(QtCore.QRect(510, 60, 71, 31))
        self.cmdDelContact.setObjectName(_fromUtf8("cmdDelContact"))
        self.cmdRefresh = QtGui.QPushButton(self.tab_Contact)
        self.cmdRefresh.setGeometry(QtCore.QRect(510, 180, 71, 31))
        self.cmdRefresh.setObjectName(_fromUtf8("cmdRefresh"))
        self.cmdModifyAlias = QtGui.QPushButton(self.tab_Contact)
        self.cmdModifyAlias.setGeometry(QtCore.QRect(510, 140, 71, 31))
        self.cmdModifyAlias.setObjectName(_fromUtf8("cmdModifyAlias"))
        self.pushButton_7 = QtGui.QPushButton(self.tab_Contact)
        self.pushButton_7.setGeometry(QtCore.QRect(510, 100, 71, 31))
        self.pushButton_7.setObjectName(_fromUtf8("pushButton_7"))
        self.tabWidget.addTab(self.tab_Contact, _fromUtf8(""))
        self.tab_Account = QtGui.QWidget()
        self.tab_Account.setObjectName(_fromUtf8("tab_Account"))
        self.label = QtGui.QLabel(self.tab_Account)
        self.label.setGeometry(QtCore.QRect(30, 60, 51, 21))
        self.label.setObjectName(_fromUtf8("label"))
        self.lineEdit_2 = QtGui.QLineEdit(self.tab_Account)
        self.lineEdit_2.setGeometry(QtCore.QRect(90, 60, 241, 21))
        self.lineEdit_2.setObjectName(_fromUtf8("lineEdit_2"))
        self.label_2 = QtGui.QLabel(self.tab_Account)
        self.label_2.setGeometry(QtCore.QRect(30, 100, 51, 21))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.lineEdit_3 = QtGui.QLineEdit(self.tab_Account)
        self.lineEdit_3.setGeometry(QtCore.QRect(90, 100, 241, 21))
        self.lineEdit_3.setObjectName(_fromUtf8("lineEdit_3"))
        self.label_3 = QtGui.QLabel(self.tab_Account)
        self.label_3.setGeometry(QtCore.QRect(30, 160, 51, 31))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.textEdit = QtGui.QTextEdit(self.tab_Account)
        self.textEdit.setGeometry(QtCore.QRect(90, 140, 431, 81))
        self.textEdit.setReadOnly(True)
        self.textEdit.setObjectName(_fromUtf8("textEdit"))
        self.pushButton_4 = QtGui.QPushButton(self.tab_Account)
        self.pushButton_4.setGeometry(QtCore.QRect(370, 250, 71, 31))
        self.pushButton_4.setObjectName(_fromUtf8("pushButton_4"))
        self.pushButton_5 = QtGui.QPushButton(self.tab_Account)
        self.pushButton_5.setGeometry(QtCore.QRect(450, 250, 71, 31))
        self.pushButton_5.setObjectName(_fromUtf8("pushButton_5"))
        self.pushButton_6 = QtGui.QPushButton(self.tab_Account)
        self.pushButton_6.setGeometry(QtCore.QRect(290, 250, 71, 31))
        self.pushButton_6.setObjectName(_fromUtf8("pushButton_6"))
        self.tabWidget.addTab(self.tab_Account, _fromUtf8(""))
        self.tab_KeyManage = QtGui.QWidget()
        self.tab_KeyManage.setObjectName(_fromUtf8("tab_KeyManage"))
        self.tableWidget = QtGui.QTableWidget(self.tab_KeyManage)
        self.tableWidget.setGeometry(QtCore.QRect(20, 30, 491, 461))
        self.tableWidget.setObjectName(_fromUtf8("tableWidget"))
        self.tableWidget.setColumnCount(5)
        self.tableWidget.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        self.tableWidget.horizontalHeader().setSortIndicatorShown(True)
        self.groupBox = QtGui.QGroupBox(self.tab_KeyManage)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 591, 481))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.pushButton = QtGui.QPushButton(self.groupBox)
        self.pushButton.setGeometry(QtCore.QRect(510, 20, 71, 31))
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.pushButton_2 = QtGui.QPushButton(self.groupBox)
        self.pushButton_2.setGeometry(QtCore.QRect(510, 60, 71, 31))
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.pushButton_3 = QtGui.QPushButton(self.groupBox)
        self.pushButton_3.setGeometry(QtCore.QRect(510, 100, 71, 31))
        self.pushButton_3.setObjectName(_fromUtf8("pushButton_3"))
        self.tabWidget.addTab(self.tab_KeyManage, _fromUtf8(""))
        self.tab_Settings = QtGui.QWidget()
        self.tab_Settings.setObjectName(_fromUtf8("tab_Settings"))
        self.label_4 = QtGui.QLabel(self.tab_Settings)
        self.label_4.setGeometry(QtCore.QRect(30, 30, 51, 21))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.comboBox = QtGui.QComboBox(self.tab_Settings)
        self.comboBox.setGeometry(QtCore.QRect(100, 30, 171, 21))
        self.comboBox.setObjectName(_fromUtf8("comboBox"))
        self.label_5 = QtGui.QLabel(self.tab_Settings)
        self.label_5.setGeometry(QtCore.QRect(20, 70, 71, 21))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.lineEdit = QtGui.QLineEdit(self.tab_Settings)
        self.lineEdit.setGeometry(QtCore.QRect(100, 70, 361, 21))
        self.lineEdit.setObjectName(_fromUtf8("lineEdit"))
        self.tabWidget.addTab(self.tab_Settings, _fromUtf8(""))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 631, 23))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuStart = QtGui.QMenu(self.menubar)
        self.menuStart.setObjectName(_fromUtf8("menuStart"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionAccount_Management = QtGui.QAction(MainWindow)
        self.actionAccount_Management.setObjectName(_fromUtf8("actionAccount_Management"))
        self.actionKeypair_Management = QtGui.QAction(MainWindow)
        self.actionKeypair_Management.setObjectName(_fromUtf8("actionKeypair_Management"))
        self.actionSettings = QtGui.QAction(MainWindow)
        self.actionSettings.setObjectName(_fromUtf8("actionSettings"))
        self.menuStart.addAction(self.actionSettings)
        self.menubar.addAction(self.menuStart.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.txtChatWindows.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt; color:#092688;\">Ray</span><span style=\" font-size:8pt;\">    2014/07/17 10:52:</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">    Wonderful!</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>", None))
        self.txtSend.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Yes, It is!</p></body></html>", None))
        self.cmdSend.setText(_translate("MainWindow", "发送", None))
        self.cmdPull.setText(_translate("MainWindow", "取回", None))
        __sortingEnabled = self.listContact.isSortingEnabled()
        self.listContact.setSortingEnabled(False)
        item = self.listContact.item(0)
        item.setText(_translate("MainWindow", "a", None))
        item = self.listContact.item(1)
        item.setText(_translate("MainWindow", "b", None))
        item = self.listContact.item(2)
        item.setText(_translate("MainWindow", "c", None))
        self.listContact.setSortingEnabled(__sortingEnabled)
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_Message), _translate("MainWindow", "消息", None))
        self.tableContact.setSortingEnabled(True)
        item = self.tableContact.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "1", None))
        item = self.tableContact.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Name", None))
        item = self.tableContact.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Alias", None))
        item = self.tableContact.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Public Key", None))
        __sortingEnabled = self.tableContact.isSortingEnabled()
        self.tableContact.setSortingEnabled(False)
        item = self.tableContact.item(0, 0)
        item.setText(_translate("MainWindow", "Yooooo", None))
        item = self.tableContact.item(0, 2)
        item.setText(_translate("MainWindow", "123", None))
        self.tableContact.setSortingEnabled(__sortingEnabled)
        self.cmdAddContact.setText(_translate("MainWindow", "添加联系人", None))
        self.cmdDelContact.setText(_translate("MainWindow", "删除联系人", None))
        self.cmdRefresh.setText(_translate("MainWindow", "刷新列表", None))
        self.cmdModifyAlias.setText(_translate("MainWindow", "更改备注", None))
        self.pushButton_7.setText(_translate("MainWindow", "导入联系人", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_Contact), _translate("MainWindow", "联系人", None))
        self.label.setText(_translate("MainWindow", "用户名:", None))
        self.label_2.setText(_translate("MainWindow", "邮  箱:", None))
        self.label_3.setText(_translate("MainWindow", "公  钥:", None))
        self.pushButton_4.setText(_translate("MainWindow", "修改信息", None))
        self.pushButton_5.setText(_translate("MainWindow", "导出联系人", None))
        self.pushButton_6.setText(_translate("MainWindow", "更新信息", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_Account), _translate("MainWindow", "账户管理", None))
        self.tableWidget.setSortingEnabled(True)
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "名称", None))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "文件名", None))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "用户名", None))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "邮箱", None))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "公钥", None))
        self.groupBox.setTitle(_translate("MainWindow", "密钥列表", None))
        self.pushButton.setText(_translate("MainWindow", "导出...", None))
        self.pushButton_2.setText(_translate("MainWindow", "导入...", None))
        self.pushButton_3.setText(_translate("MainWindow", "详细信息", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_KeyManage), _translate("MainWindow", "密钥管理", None))
        self.label_4.setText(_translate("MainWindow", "语  言:", None))
        self.label_5.setText(_translate("MainWindow", "服务器地址:", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_Settings), _translate("MainWindow", "设置", None))
        self.menuStart.setTitle(_translate("MainWindow", "Start", None))
        self.actionAccount_Management.setText(_translate("MainWindow", "Account Management", None))
        self.actionKeypair_Management.setText(_translate("MainWindow", "Keypair Management", None))
        self.actionSettings.setText(_translate("MainWindow", "Settings", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MainWindow = QtGui.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

